### PR TITLE
fix: change from throw error to output console

### LINKED ISSUE #377: [QUESTION]: Error: useCustomCompareMemo should not be used with dependencies that are all primitive values. Use React.useMemo instead.
Hi,

Quick question, I am testing your library to see changes in array of objects or objects, and have noticed that it throws an error when the array or object is set to null and keeps saying to use `useMemo` instead.

Is this normal behavior?

### PR DESCRIPTION
**Pull request by kotarella1110**
close #377

### CODE REVIEW

**Comment by simplecommerce** [comment]
@kotarella1110 The note seems clear to me, but in this PR you did not remove the check

```
  if (!(deps instanceof Array) || deps.length === 0) {
    throw new Error(
      `${name} should not be used with no dependencies. Use ${reactHookName} instead.`,
    );
  }
  if (deps.every(isPrimitive)) {
    throw new Error(
      `${name} should not be used with dependencies that are all primitive values. Use ${reactHookName} instead.`,
    );
  }
```

**Comment by kotarella1110** [comment]
@simplecommerce I think the check is required.
This will be useful for users during development.
The error will be thrown in a non-production environment.

https://github.com/kotarella1110/use-custom-compare/blob/f8a1b21ab92d33889cff269565cdf4054e69440f/src/useCustomCompareEffect.ts#L10-L12

Please explain why you want to remove this.

**Comment by simplecommerce** [comment]
@kotarella1110 It is because in my non-productive environment it is preventing me from using your library with dependencies that are objects and can be null or empty when it changes, which causes it to throw the error.

For example:
```
const SomeComponent = props => {
  const [myObj,setMyObj] = useState(props.myObj);
  
  const render = useCustomCompareMemo(() => {
    // do something and return
  },[myObj],(a,b) => isEqual(a,b));
  
  return render;
}
```

This throws an error because if the `myObj` props is `undefined` or `null` it will fail in your check.
I am forced to set the default value to `{}`.

Is this intentional?

**Comment by kotarella1110** [comment]
@simplecommerce Thanks for your reply! I understood it.
I can fix the isPremitive function or change it from `throw` to `console.error` 👍🏻 
Which do you prefer?

**Comment by simplecommerce** [comment]
@kotarella1110 I think `console.error` is good enough! thanks!

**Comment by kotarella1110** [comment]
@simplecommerce I will fix 👍🏻

**Comment by kotarella1110** [comment]
@simplecommerce please re-review 🙏🏻

**Pull request merged**
